### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by seghier** [theNewFlesh/docker_pyopenvdb#2]
Hello
Can't install the module with **pip install pyopenvdb**
I use Python 3.9

```
C:\WINDOWS\system32>pip install pyopenvdb-3.8
ERROR: Could not find a version that satisfies the requirement pyopenvdb-3.8 (from versions: none)
ERROR: No matching distribution found for pyopenvdb-3.8
```

**Comment by theNewFlesh** [comment]
It's built for python 3.7 and 3.8 and its for x86_64 Linux only (it may work on macOS...who knows).
pyopenvdb and pyopenvdb-3.8 are built to run inside docker containers, which run linux with the appropriate libraries.
I am currently not supporting python3.9 and I will never support any OS other than Linux (probably only Ubuntu at that).

**Comment by seghier** [comment]
Thank you, i use Windows 10 64 bits but still can't use it,
is it for linux only?

**Comment by theNewFlesh** [comment]
See above comment.
If you install docker on your windows machine you could use it that way (Linux runs inside the docker container).

**Comment by seghier** [comment]
Thanks , i tried it before in Ubuntu and it worked fine than it stopped after restart 
i will try with docker
