### ISSUE TITLE
Issues with processing Mounted VDBs

### ISSUE THREAD

**Issue by bhezy** [theNewFlesh/docker_pyopenvdb#5]
Hello Alex,
Thank you for developing this fantastic tool. I created a bind mounted container as follows:

docker pull thenewflesh/pyopenvdb

docker run --name pyopenvdb-wmnt -it --mount type=bind,source=c:/users/**[MY USER NAME]**/downloads/vdbs,target=/mnt thenewflesh/pyopenvdb

In which the source folder contains the attached toy VDB file ([cube.zip](https://github.com/theNewFlesh/docker_pyopenvdb/files/9067718/cube.zip)). When I run the following after the docker commands, I get the following issue:

>>> import pyopenvdb as vdb
>>> import numpy as np
>>> grid, meta = vdb.readAll('/mnt/cube.vdb')
>>> grid
[<pyopenvdb.FloatGrid object at 0x7f3c7e79a570>]

It looks as though "grid" is a variable stored in memory ... I am not necessarily sure how to access that. I cannot convert it to a numpy array either, which is my objective (I would like to export voxel grid center points to MATLAB in my Windows Host). Why might it be the case that I am unable to access the stored data? Might it be due to the way I stored the data and mounted it?

-Ben

**Comment by theNewFlesh** [comment]
FIrst thing's first:

Run this
`docker run --interactive --tty --rm thenewflesh/pyopenvdb python3.7`
then run
`import openvdb`

**Comment by theNewFlesh** [comment]
`import pyopenvdb` and `import openvdb` are not the same thing.

**Comment by theNewFlesh** [comment]
```
import openvdb as vdb
import numpy as np

src = '/root/docker_pyopenvdb/resources/cube.vdb'
grid, meta = vdb.readAll(src)
grid = grid[0]

min_ = np.array(grid.metadata['file_bbox_min'])
max_ = np.array(grid.metadata['file_bbox_max'])
shape = max_ - min_
arr = np.zeros(shape)
grid.copyToArray(arr)
arr
```
outputs:
`array([[[-0.15002441...`

**Comment by theNewFlesh** [comment]
If you git clone the docker_pyopenvdb repo, you get bin/pyopenvdb, which is a CLI I used for development.
bin/pyopenvdb --help lists all the options.
bin/pyopenvdb python will boot up the dev docker image with the repo directory mounted to /root/docker_pyopenvdb and start a python interpreter session.

**Comment by theNewFlesh** [comment]
You do not need to do this to get what you want, but you may want to, if you would like a friendly way of interacting with the pyopenvdb docker container.
