### ISSUE TITLE
Python 3.11 support?

### ISSUE THREAD

**Issue by Andrej730** [theNewFlesh/docker_pyopenvdb#6]
It's been awhile now since the last update.

**Comment by theNewFlesh** [comment]
AcademySoftwareFoundation is supposed to be officially supporting OpenVDB bindings for python, with peytondmurray leading the charge. Things got stalled, I inquired twice about it, not sure where things stand.

https://github.com/AcademySoftwareFoundation/openvdb/pull/1377/files#diff-d8b2947c50e1f20030bd56447d43d902d56e0ca7b101dd11922bbde1515d07fdR74
